# Generated by Django 4.1.7 on 2023-02-18 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('data_estimada_saida', models.DateField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('cra', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
