# Generated by Django 4.1.7 on 2023-02-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('verify_staff_user', models.BooleanField(default=False)),
                ('user_is_teacher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('data_estimada_saida', models.DateField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('cra', models.FloatField(blank=True, null=True)),
                ('curso', models.CharField(blank=True, choices=[('SI', 'Sistemas de Informação'), ('LCC', 'Lic. Ciência da Computação')], max_length=3, null=True)),
                ('nota_introducao', models.IntegerField(blank=True, null=True)),
                ('nota_POO', models.IntegerField(blank=True, null=True)),
                ('nota_linguagem', models.IntegerField(blank=True, null=True)),
                ('nota_estrutura', models.IntegerField(blank=True, null=True)),
                ('disposicao', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True)),
                ('numero_disciplinas', models.IntegerField(blank=True, null=True)),
                ('link_git_hub', models.CharField(blank=True, max_length=255, null=True)),
                ('link_linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nome', 'matricula')},
            },
        ),
    ]
