# Generated by Django 4.1.7 on 2023-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
