# Generated by Django 4.1.7 on 2023-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cra',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data_estimada_saida',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data_ingresso',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='disposicao',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='link_git_hub',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='link_linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nota_POO',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nota_estrutura',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nota_introducao',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nota_linguagem',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='numero_disciplinas',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='periodo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='periodo_ingresso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
