# Generated by Django 4.1.7 on 2023-02-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_is_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('nome', 'matricula')},
        ),
    ]
