# Generated by Django 4.1.7 on 2023-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
