# Generated by Django 4.1.7 on 2023-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_cra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
