# Generated by Django 4.1.7 on 2023-02-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='curso',
            field=models.CharField(blank=True, choices=[('SI', 'Sistemas de Informação'), ('LCC', 'Lic. Ciência da Computação')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disposicao',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_git_hub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nota_POO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nota_estrutura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nota_introducao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nota_linguagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero_disciplinas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
