# Generated by Django 4.1.7 on 2023-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='periodo_ingresso',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
