# Generated by Django 4.1.7 on 2023-03-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_periodo_ingresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='idade',
        ),
    ]
