# Generated by Django 4.1.5 on 2023-02-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculaAluno', models.CharField(max_length=255)),
                ('dataIngresso', models.DateField()),
                ('nomeAluno', models.CharField(max_length=255)),
                ('periodo', models.IntegerField()),
                ('CRA', models.FloatField()),
                ('dataEstimadaSaida', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Professor(a)',
                'verbose_name_plural': 'Professores(as)',
            },
        ),
        migrations.CreateModel(
            name='vagasEmprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVagas', models.IntegerField()),
                ('nivel', models.CharField(choices=[('B', 'Basico'), ('I', 'Intermediário'), ('A', 'Avançado')], max_length=1)),
                ('horasSemana', models.IntegerField()),
                ('valorSalario', models.FloatField()),
                ('dataCadastro', models.DateField()),
                ('tipoVaga', models.CharField(max_length=255)),
                ('beneficios', models.CharField(max_length=255)),
                ('tituloVaga', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('dataFechamento', models.DateField()),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.professor')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioComposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.aluno')),
                ('id_user_aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professorComposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.professor')),
                ('id_user_professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.aluno')),
                ('IDVAGA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.vagasemprego')),
            ],
        ),
        migrations.CreateModel(
            name='areaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesseProfessor', models.CharField(max_length=255)),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.professor')),
            ],
        ),
    ]
