# Generated by Django 4.1.5 on 2023-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matriculaAluno',
            field=models.CharField(max_length=255),
        ),
    ]
