# Generated by Django 4.1.5 on 2023-02-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='user_id',
            new_name='user',
        ),
    ]
