# Generated by Django 4.1.5 on 2023-02-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_user_id_aluno_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarioComposto',
        ),
    ]
