FROM python:3

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /code

COPY . .
COPY ./opportunity/.env /code/opportunity/.env


COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "/entrypoint.sh"]