version: '3.8'
name: opportunity_full
services:
  django:
    image: kawhan/opportunity:latest
    container_name: django_full
    volumes:
      - .:/usr/src/app
    env_file:
      - ./opportunity/.env
    ports:
      - "80:8000"
    depends_on:
      - pgdb
      - redis
  redis:
    image: "redis:latest"
    environment:
      - REDIS_HOST=redis
  pgdb:
    image: "postgres:latest"
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql 
    ports:
      - "5432:5432"
volumes:
    pgdata:
      driver: local