# Generated by Django 4.1.7 on 2023-02-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Professor(a)',
                'verbose_name_plural': 'Professores(as)',
            },
        ),
        migrations.CreateModel(
            name='vagasEmprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVagas', models.IntegerField()),
                ('nivel', models.CharField(choices=[('B', 'Basico'), ('I', 'Intermediário'), ('A', 'Avançado')], max_length=1)),
                ('horasSemana', models.IntegerField()),
                ('valorSalario', models.FloatField()),
                ('dataCadastro', models.DateField()),
                ('tipoVaga', models.CharField(max_length=255)),
                ('beneficios', models.CharField(max_length=255)),
                ('tituloVaga', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('dataFechamento', models.DateField()),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.professor')),
            ],
        ),
    ]
