# Generated by Django 4.1.7 on 2023-02-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagasemprego',
            name='link_vaga',
            field=models.CharField(default='', max_length=255, verbose_name='Link da vaga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PE', 'Projeto de extensão'), ('PP', 'Projeto de Pesquisa'), ('ES', 'Estágio')], max_length=2),
        ),
    ]
