# Generated by Django 4.1.7 on 2023-02-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_vagasemprego_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagasemprego',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='project.professor'),
            preserve_default=False,
        ),
    ]
