# Generated by Django 4.1.7 on 2023-04-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_vagasemprego_tipo_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PP', 'Projeto de Pesquisa'), ('PE', 'Projeto de extensão'), ('ES', 'Estágio')], max_length=2),
        ),
    ]
