# Generated by Django 4.1.7 on 2023-02-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_vagasemprego_datacadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagasemprego',
            old_name='professor_id',
            new_name='professor',
        ),
    ]
