# Generated by Django 4.1.7 on 2023-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_vagasemprego_tipo_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PP', 'Projeto de Pesquisa'), ('ES', 'Estágio'), ('PE', 'Projeto de extensão')], max_length=2),
        ),
    ]
