# Generated by Django 4.1.7 on 2023-02-23 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_vagasemprego_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='dataCadastro',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data de cadastro'),
        ),
    ]
