# Generated by Django 4.1.7 on 2023-02-23 20:21

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_vagasemprego_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='dataCadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='descricao',
            field=tinymce.models.HTMLField(verbose_name='Descrição'),
        ),
    ]
