# Generated by Django 4.1.7 on 2023-02-19 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='dataCadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
