# Generated by Django 4.1.7 on 2023-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_vagasemprego_tipo_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='disponivel',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PE', 'Projeto de extensão'), ('ES', 'Estágio'), ('PP', 'Projeto de Pesquisa')], max_length=2),
        ),
    ]
