# Generated by Django 4.1.7 on 2023-02-19 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_vagasemprego_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='beneficios',
            field=models.CharField(max_length=255, verbose_name='Beneficios'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='dataCadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='dataFechamento',
            field=models.DateField(verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='descricao',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='horasSemana',
            field=models.IntegerField(verbose_name='Horas Semana'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='numeroVagas',
            field=models.IntegerField(verbose_name='Número de vagas'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipoVaga',
            field=models.CharField(max_length=255, verbose_name='Tipo da Vaga'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tituloVaga',
            field=models.CharField(max_length=255, verbose_name='Titulo da Vaga'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='valorSalario',
            field=models.FloatField(verbose_name='Valor Salario'),
        ),
    ]
