# Generated by Django 4.1.7 on 2023-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_curso_userprofile_disposicao_and_more'),
        ('project', '0005_alter_vagasemprego_datacadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagasemprego',
            name='aluno',
            field=models.ManyToManyField(blank=True, to='accounts.userprofile'),
        ),
    ]
