# Generated by Django 4.1.7 on 2023-05-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_vagasemprego_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='pdf',
            field=models.CharField(max_length=255, verbose_name='Link do pdf'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PP', 'Projeto de Pesquisa'), ('ES', 'Estágio'), ('PE', 'Projeto de extensão')], max_length=2),
        ),
    ]
