# Generated by Django 4.1.7 on 2023-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_vagasemprego_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagasemprego',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
