# Generated by Django 4.1.7 on 2023-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_vagasemprego_beneficios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
