# Generated by Django 4.1.7 on 2023-04-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_vagasemprego_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagasemprego',
            name='nivel',
        ),
    ]
